services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' & yarn build --watch & yarn build:css --watch"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  redis:
    image: redis:6.2.6-alpine
    hostname: redis
    volumes:
      - ./tmp/redis:/data/db
    ports:
      - 6379:6379
